
import sys
import os
kgnet_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
inference_dir = os.path.abspath(os.path.dirname(__file__))

sys.path.append(kgnet_dir)
sys.path.append(inference_dir)

from Constants import *
from GMLaaS.Inference_pipeline import perform_inference
from fastapi import FastAPI
from uvicorn import run
from typing import List
from pydantic import BaseModel
import traceback

app = FastAPI()
#HOST = '127.0.0.1'
HOST = '0.0.0.0'
PORT = 5000

class InferenceRequest(BaseModel):
    model_id : int
    named_graph_uri : str
    sparqlEndpointURL : str
    dataQuery : List[str]
    targetNodesQuery : str
    topk: int = 1


@app.post("/gml_inference/mid/{mid}")
async def run_inference(mid:int,inference_request: InferenceRequest):

    dic_results = {"https://dblp.org/rec/books/sp/22/0001MQWH22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/BarkhamBS22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/BuhnovaKGWCC22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/FernandezSTM22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/KhatoonAHA22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/KirwanD22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/LiYTR22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/Moraitis22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/NagyS22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/Rassia22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/Tsoniotis22":"Artificial Intelligence, Machine Learning, and Optimization Tools for Smart Cities",
"https://dblp.org/rec/books/sp/22/Atanassov22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/AtanassovSSVS22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/BrandaoG22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/DockhornK22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/FilhoRCC22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/GarvanovaGJ22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/ItoHSS22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/KaltenbornHK22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/Katsumata22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/PetrovaKA22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/QuYT22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/RosasHS22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/SaariRHH22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/SandersHTBLG22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/SchneiderWRP22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/Sgurev22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/SgurevDD22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/StoyanovGPD22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/TasminRISAZR22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/TenekedjievNFSN22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/WangHYK22":"Advances in Intelligent Systems Research and Innovation",
"https://dblp.org/rec/books/sp/22/BhalwankarT22a":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/BhalwankarT22b":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/BhalwankarT22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/HermansMT22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/MentsBT22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/MentsRT22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/MentsT0R22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/MentsT22a":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/MentsT22b":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/MentsT22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22a":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22b":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22c":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22d":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22e":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22f":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22g":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22h":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/Treur22i":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/TreurG22":"Mental Models and Their Dynamics, Adaptation, and Control",
"https://dblp.org/rec/books/sp/22/CozzolinoV22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/FerraraF22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/GragnanielloMV22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/HaoBGMBXYSHYZD22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/Hernandez-OrtegaTFM22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/IbsenRFD022":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/JiangW0L22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/KorshunovM22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/Laas-MikkoKDT22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/LiSQL22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/Majumdar0V022":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/NguyenYE22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/PicMTD22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/RotPS22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/RoyJ0D22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/ScherhagR022":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/SpreeuwersSVK22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/TolosanaRV0VLNYERGSDARFMOKJKT22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/TolosanaVFMO22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/WangSW0HL22":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/XuRR022":"Handbook of Digital Face Manipulation and Detection",
"https://dblp.org/rec/books/sp/22/PRT2022":"Springer Optimization and Its Applications",
"https://dblp.org/rec/books/sp/22/RTVB2022":"Advances in Computer Vision and Pattern Recognition",
"https://dblp.org/rec/books/sp/22/SJK2022":"Studies in Systems, Decision and Control",
"https://dblp.org/rec/books/ws/Burgin22":"World Scientific Series in Information Studies",
"https://dblp.org/rec/books/ws/Kizilova20":"Series in Mathematical Biology and Medicine",
"https://dblp.org/rec/books/ws/LeeDG22":"Singapore University of Social Sciences - World Scientific Future Economy Series",
"https://dblp.org/rec/books/ws/MallC22":"Series on Deep Learning Neural Networks",
"https://dblp.org/rec/books/ws/Roseman22":"Series on Knots and Everything",
"https://dblp.org/rec/books/ws/Simos22":"Computational, Numerical and Mathematical Methods in Sciences and Engineering",
"https://dblp.org/rec/conf/3pgcic/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/nafips/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/clawar/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/cores/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/deepbdb/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/dcai/2021-1":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/ihiet/2021paris":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/nbis/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/simultech/2020s":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/rev/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/intellisys/2021-1":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/intellisys/2021-2":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/intellisys/2021-3":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/mco/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/imis/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/icict/2021-1":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/icict/2021-2":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/icict/2021-3":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/ncs/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/mis4tel/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/pacbb/2021":"Lecture Notes in Networks and Systems",
"https://dblp.org/rec/conf/3pgcic/AhmedAETLH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/AmpriritQBIMB21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/BalzanoBZ21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/BarolliCF21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/BarolliSBT21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/CostaDDVS21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/DominicPKSS21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/FuchigamiI21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/JorgeBS21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/KohanaSO21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/MirdadH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/NishiiIB21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/OgielaTO21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/PioliTNMJD21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/SagarAH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/SaitoOHYKB21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/SchepersEECLH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/SugitaS21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/TadaMUIB21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/TrochHVBLH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/VannesteBBVMMLH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/VannesteWVMMLH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/XuBASKB21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/YahadaI21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/YamashitaSD21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/Yoshihisa21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/BylykbashiQAIMB21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/HoogAALH21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/KambleC21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/KatoHKN21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/MexicanoCCCLR21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/SuranthaNHCS21":"3PGCIC",
"https://dblp.org/rec/conf/3pgcic/ZhangJZZC21":"3PGCIC",
"https://dblp.org/rec/conf/ctrsa/Bultel22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/CaoSCCFW22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/Chevallier-Mames22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/CidIR22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/CuiHWW22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/FouotsaP22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/WuX22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/AtapoorSA22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/BienstockDT22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/BossertLLS22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/BrollCDFLNT22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/Chuengsatiansup22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/ElkhatibKA22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/FanLNLW22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/FaonioFNS22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/GalindoL22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/GellertJLN22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/GjosteenRW22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/KimPP22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/Martinez22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/MukhtarBPK22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/VittoB22":"CT-RSA",
"https://dblp.org/rec/conf/ctrsa/Chi-DominguezR22":"",
"https://dblp.org/rec/conf/ctrsa/Rosie22":"",
"https://dblp.org/rec/conf/padl/BellusciMR22":"",
"https://dblp.org/rec/conf/padl/BistarelliMT22":"",
"https://dblp.org/rec/conf/blockchain/2021":"",
"https://dblp.org/rec/conf/iceit/UbaniN22":"",
"https://dblp.org/rec/conf/caldam/DuttaR22":"",
"https://dblp.org/rec/conf/wacv/JandialBCCSK22":"",
"https://dblp.org/rec/conf/wacv/VepaCNLSVJYSDDL22":"",
"https://dblp.org/rec/conf/rweb/dAmato21":"",
"https://dblp.org/rec/conf/ttc/CopeiKZ21":"",
"https://dblp.org/rec/conf/comad/OswaldSB22":"",
"https://dblp.org/rec/conf/se/Mayr-DornVBKCEM22":"",
"https://dblp.org/rec/conf/nbis/BarolliBQSB21":"",
"https://dblp.org/rec/conf/ccnc/AissaLSR22":"",
"https://dblp.org/rec/conf/ccnc/BoselloT022":"",
"https://dblp.org/rec/conf/ccnc/EngelhardtHG22":"",
"https://dblp.org/rec/conf/ccnc/HajizadehJB22":"",
"https://dblp.org/rec/conf/ccnc/HoqueHH22":"",
"https://dblp.org/rec/conf/ccnc/KandaKYN22":"",
"https://dblp.org/rec/conf/padl/2022":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/caldam/2022":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/vmcai/2022":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/rweb/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/bigdata2/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/mod/2021-1":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/mod/2021-2":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/ctrsa/2022":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/css/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/tpctc/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/lfcs/2022":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/lcpc/2020":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/aims2/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/esorics/2021cicps":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/esorics/2021dpm":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/mabs/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/stacom-ws/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/icdcit/2022":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/vstte/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/iwdw/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/icws2/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/adma/2021-1":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/adma/2021-2":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/iciot2/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/miccai/2021dfuc":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/icbc/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/agi/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/npc/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/space/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/services2/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/iccc2/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/wine/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/dai2/2021":"Lecture Notes in Computer Science",
"https://dblp.org/rec/conf/padl/AriasCG22":"PADL",
"https://dblp.org/rec/conf/padl/Balduccini22":"PADL",
"https://dblp.org/rec/conf/padl/BurghardtHG22":"PADL",
"https://dblp.org/rec/conf/padl/EvansFW22":"PADL",
"https://dblp.org/rec/conf/padl/FaberMC22":"PADL",
"https://dblp.org/rec/conf/padl/FortiB22":"PADL",
"https://dblp.org/rec/conf/padl/Janhunen22":"PADL",
"https://dblp.org/rec/conf/padl/RealeCLR22":"PADL",
"https://dblp.org/rec/conf/padl/Tajelipirbazari22":"PADL",
"https://dblp.org/rec/conf/padl/TardivoP22":"PADL",
"https://dblp.org/rec/conf/padl/VaranasiASLBG22":"PADL",
"https://dblp.org/rec/conf/blockchain/Ako-NaiMT21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/Banerjee21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/BurkertHLRSSVJ21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/BurkertHWJ21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/CaceresBPL21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/CarareCGF21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/DArcoM21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/Dalwani21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/DongMW21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/GointBD21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/GoncalvesFGPP21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/GouiaaHJ21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/GouiaaHJ21a":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/GutierrezHNV21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/HdhiliGJ21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/Jimenez-Serrania21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/KanthMT21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/KrambergerWK21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/LageSZ21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/MartinJ0K21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/MezquitaGPC21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/MugunthanRK21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/NdiayeK21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/PiedrahitaBR21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/PillaiSR21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/PincheiraVG21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/PrechtG21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/RichardPTS21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/SchmelzPNG21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/ShuklaTHB21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/SilvaTB21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/SivianesB21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/StaderiniB21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/Stefanescu21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/StefanescuGMUU21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/SuvajdzicSK21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/TadepalliT21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/blockchain/Vieira21":"BLOCKCHAIN",
"https://dblp.org/rec/conf/iceit/Alkhalifah22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ChenHTLHH22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ChenLZQ22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ChenZMG22":"ICEIT",
"https://dblp.org/rec/conf/iceit/FanR22":"ICEIT",
"https://dblp.org/rec/conf/iceit/FuZ22":"ICEIT",
"https://dblp.org/rec/conf/iceit/GangHS22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Hu22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Li22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Li22a":"ICEIT",
"https://dblp.org/rec/conf/iceit/Li22b":"ICEIT",
"https://dblp.org/rec/conf/iceit/LiG22":"ICEIT",
"https://dblp.org/rec/conf/iceit/LinWZLLX22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Liu22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Liu22a":"ICEIT",
"https://dblp.org/rec/conf/iceit/LiuNFZYW22":"ICEIT",
"https://dblp.org/rec/conf/iceit/LiuZ22":"ICEIT",
"https://dblp.org/rec/conf/iceit/LuoWZ22":"ICEIT",
"https://dblp.org/rec/conf/iceit/LuoXJM22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Muller22":"ICEIT",
"https://dblp.org/rec/conf/iceit/NiHYHZCS22":"ICEIT",
"https://dblp.org/rec/conf/iceit/OoiG22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Pearce22":"ICEIT",
"https://dblp.org/rec/conf/iceit/QianLWD22":"ICEIT",
"https://dblp.org/rec/conf/iceit/QinW22":"ICEIT",
"https://dblp.org/rec/conf/iceit/RaoHL22":"ICEIT",
"https://dblp.org/rec/conf/iceit/RenTWL22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ShiYY22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Simon22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Sun22":"ICEIT",
"https://dblp.org/rec/conf/iceit/TaoXLS22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Wang22":"ICEIT",
"https://dblp.org/rec/conf/iceit/WangL22":"ICEIT",
"https://dblp.org/rec/conf/iceit/WangL22a":"ICEIT",
"https://dblp.org/rec/conf/iceit/WangZMLG22":"ICEIT",
"https://dblp.org/rec/conf/iceit/WeiY22":"ICEIT",
"https://dblp.org/rec/conf/iceit/WenhuaZ22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Yang22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Yue22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Zhang22":"ICEIT",
"https://dblp.org/rec/conf/iceit/Zhang22a":"ICEIT",
"https://dblp.org/rec/conf/iceit/ZhangF22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ZhangM22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ZhangSCY22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ZhangT22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ZhaoL22":"ICEIT",
"https://dblp.org/rec/conf/iceit/ZhouYC22":"ICEIT",
"https://dblp.org/rec/conf/nafips/2020":"Advances in Intelligent Systems and Computing",
"https://dblp.org/rec/conf/ukci/2021":"Advances in Intelligent Systems and Computing",
"https://dblp.org/rec/conf/cisis-spain/2021":"Advances in Intelligent Systems and Computing",
"https://dblp.org/rec/conf/softcomp/2021":"Advances in Intelligent Systems and Computing",
"https://dblp.org/rec/conf/rie/2021":"Advances in Intelligent Systems and Computing",
"https://dblp.org/rec/conf/nafips/AlvarezSSCK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/AndradeBTS20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/ArnettEKB20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/BarthCM21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/BedeW21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/BergamaschiJSO20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/BergamaschiS21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/BihaniR21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/BokatiKK21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/BokatiVK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/CastiblancoFRM20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/CeberioKK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/ChhabraKC20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/CohenBCKK21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/CohenN21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/CostaB21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/DeGrooteC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/DujmovicT21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/DunlapCH21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/ErnestKA20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Figueroa-Garcia21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/FrancoC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/GarciaF20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/GarciaSK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/GarciaT20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/HirschC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/HozaifaM20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/HuSWW21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/JingZHR21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/KoshelevaK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/KoshelevaK21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/KoshelevaK21a":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Kosko21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/LaiateEPB21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/LiC20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/LiC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/LongoLPEBM21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/LopesPBES21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MacielBG20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MacmannC20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MacmannCC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MayadeviMSC20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MelinMCP20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MisraR20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MisraR21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/MizukoshiL21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Mockor20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Murphy21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Noronha21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/OGradyVC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PalmerC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PandaK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PasekaSS20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PatelC20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PatelS20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PickeringC20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PickeringC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/PintoEB20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/RamirezMP20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/RingenbergRS20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/RingenbergSR21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/SabounchiW21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/SathyanYFBDMGMA21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Servin21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/ServinK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/ServinKK21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Skrjanc20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/StrzinarS21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Stuhlman21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/SuritaLG21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/TerryC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/TrincaWE20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/UrendaCC0EK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/UrendaHVK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/UrendaK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/UrendaKCK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/UrendaSKK21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/ValeraCKK20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/VianaC20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/VianaC20a":"NAFIPS",
"https://dblp.org/rec/conf/nafips/VianaC21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/VianaC21a":"NAFIPS",
"https://dblp.org/rec/conf/nafips/Wasques21":"NAFIPS",
"https://dblp.org/rec/conf/nafips/WasquesEBP20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/WasquesPEB20":"NAFIPS",
"https://dblp.org/rec/conf/nafips/ZapataKK21":"NAFIPS",
"https://dblp.org/rec/conf/cores/Apiecionek21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/FlasinskiJP21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/GruzewskiP21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/KiedrowskiZM21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/KlikowskiB21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/KomisarekPSPKC21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/KrupskiRGI21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/KudlacikO21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/Lasek21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/LebskaOOP21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/LuntovskyyH21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/MitraCC21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/NowakPJ21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/OgawaEKK21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/OkarmaK21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/PotempaP21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/Przewlocka-RusK21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/Sluzek21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/StachowiakKS21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/TrajdosK21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/WalczynskiF21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/WegrzynPBBP21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/ZyblewskiPKC21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/AgusaEKK21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/ChmielewskiNO21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/ChmielowskiK21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/GlobaNPZY21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/KuchczynskiPPC21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/Mazur21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/MichalakKLO21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/NowosielskiK21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/RyabininF21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/cores/SilvaG21":"CORES/IP&C/ACS",
"https://dblp.org/rec/conf/caldam/AnilC22":"CALDAM",
"https://dblp.org/rec/conf/caldam/BarrosOPS22":"CALDAM",
"https://dblp.org/rec/conf/caldam/BensmailHLS22":"CALDAM",
"https://dblp.org/rec/conf/caldam/BhabakH22":"CALDAM",
"https://dblp.org/rec/conf/caldam/BokBFHJ22":"CALDAM",
"https://dblp.org/rec/conf/caldam/BuchinR22":"CALDAM",
"https://dblp.org/rec/conf/caldam/DasDMS22":"CALDAM",
"https://dblp.org/rec/conf/caldam/DondiP22":"CALDAM",
"https://dblp.org/rec/conf/caldam/GaikwadMT22":"CALDAM",
"https://dblp.org/rec/conf/caldam/GuoL22":"CALDAM",
"https://dblp.org/rec/conf/caldam/JainPR22":"CALDAM",
"https://dblp.org/rec/conf/caldam/LingasPS22":"CALDAM",
"https://dblp.org/rec/conf/caldam/MisraN22":"CALDAM",
"https://dblp.org/rec/conf/caldam/MohanapriyaRS22":"CALDAM",
"https://dblp.org/rec/conf/caldam/MouraOW22":"CALDAM",
"https://dblp.org/rec/conf/caldam/PandaS22":"CALDAM",
"https://dblp.org/rec/conf/caldam/PrashantFR22":"CALDAM",
"https://dblp.org/rec/conf/caldam/ShaluA22":"CALDAM",
"https://dblp.org/rec/conf/caldam/ShaluK22":"CALDAM",
"https://dblp.org/rec/conf/caldam/Storandt22":"CALDAM",
"https://dblp.org/rec/conf/caldam/TripathiKPPW22":"CALDAM",
"https://dblp.org/rec/conf/caldam/TuiteTC22":"CALDAM",
"https://dblp.org/rec/conf/caldam/WojciechowskiSV22":"CALDAM",
"https://dblp.org/rec/conf/wacv/0001HM22":"WACV",
"https://dblp.org/rec/conf/wacv/0001R22":"WACV",
"https://dblp.org/rec/conf/wacv/0001R22a":"WACV",
"https://dblp.org/rec/conf/wacv/0001SDI22":"WACV",
"https://dblp.org/rec/conf/wacv/0002R22":"WACV",
"https://dblp.org/rec/conf/wacv/0007E22":"WACV",
"https://dblp.org/rec/conf/wacv/0035KZCLW22":"WACV",
"https://dblp.org/rec/conf/wacv/AbdelhamedYPBCK22":"WACV",
"https://dblp.org/rec/conf/wacv/AbdelreheemUSYC22":"WACV",
"https://dblp.org/rec/conf/wacv/AbuolaimAB22":"WACV",
"https://dblp.org/rec/conf/wacv/AgarwalPZG22":"WACV",
"https://dblp.org/rec/conf/wacv/AhmedMM22":"WACV",
"https://dblp.org/rec/conf/wacv/AkadaBAW22":"WACV",
"https://dblp.org/rec/conf/wacv/AlahmadiH22":"WACV",
"https://dblp.org/rec/conf/wacv/AlbertOAOM22":"WACV",
"https://dblp.org/rec/conf/wacv/AliSHW22":"WACV",
"https://dblp.org/rec/conf/wacv/AlizadehCA22":"WACV",
"https://dblp.org/rec/conf/wacv/AljundiCR22":"WACV",
"https://dblp.org/rec/conf/wacv/AmacSBIC22":"WACV",
"https://dblp.org/rec/conf/wacv/AmosyC22":"WACV",
"https://dblp.org/rec/conf/wacv/AndersonF22":"WACV",
"https://dblp.org/rec/conf/wacv/Atienza22":"WACV",
"https://dblp.org/rec/conf/wacv/AzulayHVBB22":"WACV",
"https://dblp.org/rec/conf/wacv/BaekCZSR22":"WACV",
"https://dblp.org/rec/conf/wacv/BaktashmotlaghC22":"WACV",
"https://dblp.org/rec/conf/wacv/BammeyNGGCM22":"WACV",
"https://dblp.org/rec/conf/wacv/BashkirovaUS22":"WACV",
"https://dblp.org/rec/conf/wacv/BateniBMW22":"WACV",
"https://dblp.org/rec/conf/wacv/BauerPV22":"WACV",
"https://dblp.org/rec/conf/wacv/BelharbiSPAMG22":"WACV",
"https://dblp.org/rec/conf/wacv/BenbarkaHRZ22":"WACV",
"https://dblp.org/rec/conf/wacv/Bengar0LR22":"WACV",
"https://dblp.org/rec/conf/wacv/BetteBBLK22":"WACV",
"https://dblp.org/rec/conf/wacv/BevandicOGSS22":"WACV",
"https://dblp.org/rec/conf/wacv/BharadwajJNT22":"WACV",
"https://dblp.org/rec/conf/wacv/BhaskaraAJL22":"WACV",
"https://dblp.org/rec/conf/wacv/BhattacharjeeES22":"WACV",
"https://dblp.org/rec/conf/wacv/BiniciPML22":"WACV",
"https://dblp.org/rec/conf/wacv/BirhanePW22":"WACV",
"https://dblp.org/rec/conf/wacv/BitenGK22":"WACV",
"https://dblp.org/rec/conf/wacv/BitenMGK22":"WACV",
"https://dblp.org/rec/conf/wacv/BlackSPS22":"WACV",
"https://dblp.org/rec/conf/wacv/BlantonWJ22":"WACV",
"https://dblp.org/rec/conf/wacv/BoydBC22":"WACV",
"https://dblp.org/rec/conf/wacv/BucciBCT22":"WACV",
"https://dblp.org/rec/conf/wacv/ByunGK22":"WACV",
"https://dblp.org/rec/conf/wacv/ByunGK22a":"WACV",
"https://dblp.org/rec/conf/wacv/CantariniTNO22":"WACV",
"https://dblp.org/rec/conf/wacv/CaoBTAL0SE22":"WACV",
"https://dblp.org/rec/conf/wacv/CardaceLRSS22":"WACV",
"https://dblp.org/rec/conf/wacv/CardaceRSS22":"WACV",
"https://dblp.org/rec/conf/wacv/ChenGM22":"WACV",
"https://dblp.org/rec/conf/wacv/ChenLTP22":"WACV",
"https://dblp.org/rec/conf/wacv/ChenWC22":"WACV",
"https://dblp.org/rec/conf/wacv/ChenZ22":"WACV",
"https://dblp.org/rec/conf/wacv/ChengLA22":"WACV",
"https://dblp.org/rec/conf/wacv/ChengLZHNC0W22":"WACV",
"https://dblp.org/rec/conf/wacv/ChiangTTLC22":"WACV",
"https://dblp.org/rec/conf/wacv/ChoLKJL22":"WACV",
"https://dblp.org/rec/conf/wacv/ChoPK22":"WACV",
"https://dblp.org/rec/conf/wacv/ChungKK22":"WACV",
"https://dblp.org/rec/conf/wacv/CostaZROSM022":"WACV",
"https://dblp.org/rec/conf/wacv/CuiCXJ0CLL22":"WACV",
"https://dblp.org/rec/conf/wacv/DCruzTGK22":"WACV",
"https://dblp.org/rec/conf/wacv/DasJYA22":"WACV",
"https://dblp.org/rec/conf/wacv/DebSBAAR22":"WACV",
"https://dblp.org/rec/conf/wacv/DesaiG22":"WACV",
"https://dblp.org/rec/conf/wacv/DeyB22":"WACV",
"https://dblp.org/rec/conf/wacv/Dhingra22":"WACV",
"https://dblp.org/rec/conf/wacv/DoshiY22":"WACV",
"https://dblp.org/rec/conf/wacv/DoshiY22a":"WACV",
"https://dblp.org/rec/conf/wacv/DouradoGC22":"WACV",
"https://dblp.org/rec/conf/wacv/DrenkowFB22":"WACV",
"https://dblp.org/rec/conf/wacv/Du0CLSRC22":"WACV",
"https://dblp.org/rec/conf/wacv/DuggalWMMLWU22":"WACV",
"https://dblp.org/rec/conf/wacv/EbrahimpourQB22":"WACV",
"https://dblp.org/rec/conf/wacv/ElfekiWB22":"WACV",
"https://dblp.org/rec/conf/wacv/Fan022":"WACV",
"https://dblp.org/rec/conf/wacv/FarberGLN22":"WACV",
"https://dblp.org/rec/conf/wacv/FelVCS22":"WACV",
"https://dblp.org/rec/conf/wacv/FobiMWMT22":"WACV",
"https://dblp.org/rec/conf/wacv/FreerYJCC22":"WACV",
"https://dblp.org/rec/conf/wacv/FuCHD22":"WACV",
"https://dblp.org/rec/conf/wacv/FurukawaMSK22":"WACV",
"https://dblp.org/rec/conf/wacv/GabeurN0AS22":"WACV",
"https://dblp.org/rec/conf/wacv/GaddeJ22":"WACV",
"https://dblp.org/rec/conf/wacv/GaneshCYCW22":"WACV",
"https://dblp.org/rec/conf/wacv/GazakMSPF22":"WACV",
"https://dblp.org/rec/conf/wacv/GhoddoosianSA22":"WACV",
"https://dblp.org/rec/conf/wacv/GodiJSC22":"WACV",
"https://dblp.org/rec/conf/wacv/GolestanehDK22":"WACV",
"https://dblp.org/rec/conf/wacv/GomesCAMN22":"WACV",
"https://dblp.org/rec/conf/wacv/GomezRFG22":"WACV",
"https://dblp.org/rec/conf/wacv/GongCCW22":"WACV",
"https://dblp.org/rec/conf/wacv/GongKZ0D22":"WACV",
"https://dblp.org/rec/conf/wacv/GopalakrishnanS22":"WACV",
"https://dblp.org/rec/conf/wacv/GrasshofB22":"WACV",
"https://dblp.org/rec/conf/wacv/Guan0LCW0M22":"WACV",
"https://dblp.org/rec/conf/wacv/GuanTHYQ22":"WACV",
"https://dblp.org/rec/conf/wacv/Guo0CYUSS22":"WACV",
"https://dblp.org/rec/conf/wacv/HagemannKS22":"WACV",
"https://dblp.org/rec/conf/wacv/HanCTG0PW22":"WACV",
"https://dblp.org/rec/conf/wacv/HanMMGTM22":"WACV",
"https://dblp.org/rec/conf/wacv/HarishNR22":"WACV",
"https://dblp.org/rec/conf/wacv/HartleySWM22":"WACV",
"https://dblp.org/rec/conf/wacv/HatamizadehTN0M22":"WACV",
"https://dblp.org/rec/conf/wacv/HatayaZYN22":"WACV",
"https://dblp.org/rec/conf/wacv/HaurumMEM22":"WACV",
"https://dblp.org/rec/conf/wacv/HayashidaNB22":"WACV",
"https://dblp.org/rec/conf/wacv/HeB22":"WACV",
"https://dblp.org/rec/conf/wacv/HeZ22":"WACV",
"https://dblp.org/rec/conf/wacv/HicksonRE22":"WACV",
"https://dblp.org/rec/conf/wacv/HinzFWSW22":"WACV",
"https://dblp.org/rec/conf/wacv/HoZ22":"WACV",
"https://dblp.org/rec/conf/wacv/HongKBOL22":"WACV",
"https://dblp.org/rec/conf/wacv/HongYCK22":"WACV",
"https://dblp.org/rec/conf/wacv/HoritaASYZ22":"WACV",
"https://dblp.org/rec/conf/wacv/HorvathPSAESLEM22":"WACV",
"https://dblp.org/rec/conf/wacv/HouDD22":"WACV",
"https://dblp.org/rec/conf/wacv/HouK22":"WACV",
"https://dblp.org/rec/conf/wacv/HsiehCL22":"WACV",
"https://dblp.org/rec/conf/wacv/HuangWYSLTW22":"WACV",
"https://dblp.org/rec/conf/wacv/HuangZLB22":"WACV",
"https://dblp.org/rec/conf/wacv/Huberman-Spiegelglas22":"WACV",
"https://dblp.org/rec/conf/wacv/HusseinTCEG22":"WACV",
"https://dblp.org/rec/conf/wacv/Huynh0MRH22":"WACV",
"https://dblp.org/rec/conf/wacv/HuynhKWMK22":"WACV",
"https://dblp.org/rec/conf/wacv/HwangOK22":"WACV",
"https://dblp.org/rec/conf/wacv/IbrahimiSRC22":"WACV",
"https://dblp.org/rec/conf/wacv/InkawhichIDLC22":"WACV",
"https://dblp.org/rec/conf/wacv/IssenhuthTPM22":"WACV",
"https://dblp.org/rec/conf/wacv/IzhakLT22":"WACV",
"https://dblp.org/rec/conf/wacv/JakoelES22":"WACV",
"https://dblp.org/rec/conf/wacv/JayasingheHAKRJ22":"WACV",
"https://dblp.org/rec/conf/wacv/JeevanS22":"WACV",
"https://dblp.org/rec/conf/wacv/JeongKLHHC22":"WACV",
"https://dblp.org/rec/conf/wacv/JeongKMJGC22":"WACV",
"https://dblp.org/rec/conf/wacv/JewellKM22":"WACV",
"https://dblp.org/rec/conf/wacv/JiWZYC0D22":"WACV",
"https://dblp.org/rec/conf/wacv/JuLHL22":"WACV",
"https://dblp.org/rec/conf/wacv/JungLH22":"WACV",
"https://dblp.org/rec/conf/wacv/KanHHTB022":"WACV",
"https://dblp.org/rec/conf/wacv/KanchanaSYS22":"WACV",
"https://dblp.org/rec/conf/wacv/KarmaliAHAJB22":"WACV",
"https://dblp.org/rec/conf/wacv/KataokaHHYI22":"WACV",
"https://dblp.org/rec/conf/wacv/KatoNYCS22":"WACV",
"https://dblp.org/rec/conf/wacv/KayaKSFG22":"WACV",
"https://dblp.org/rec/conf/wacv/KhanRN22":"WACV",
"https://dblp.org/rec/conf/wacv/Khindkar0BSSJ22":"WACV",
"https://dblp.org/rec/conf/wacv/KimJLKK22":"WACV",
"https://dblp.org/rec/conf/wacv/KimLKJK22":"WACV",
"https://dblp.org/rec/conf/wacv/Kobayashi22":"WACV",
"https://dblp.org/rec/conf/wacv/KocasariDTY22":"WACV",
"https://dblp.org/rec/conf/wacv/KongKKMK22":"WACV",
"https://dblp.org/rec/conf/wacv/KongPG22":"WACV",
"https://dblp.org/rec/conf/wacv/KucerOC022":"WACV",
"https://dblp.org/rec/conf/wacv/Kumar0S22":"WACV",
"https://dblp.org/rec/conf/wacv/KwonPKWSF22":"WACV",
"https://dblp.org/rec/conf/wacv/LazarouSA22":"WACV",
"https://dblp.org/rec/conf/wacv/LeeCC22":"WACV",
"https://dblp.org/rec/conf/wacv/LeeHPL22":"WACV",
"https://dblp.org/rec/conf/wacv/LeeLK22":"WACV",
"https://dblp.org/rec/conf/wacv/LeeLLKHL22":"WACV",
"https://dblp.org/rec/conf/wacv/LeeYW22":"WACV",
"https://dblp.org/rec/conf/wacv/LeottaRM22":"WACV",
"https://dblp.org/rec/conf/wacv/LerouxLS22":"WACV",
"https://dblp.org/rec/conf/wacv/LiDG22":"WACV",
"https://dblp.org/rec/conf/wacv/LiF0K22":"WACV",
"https://dblp.org/rec/conf/wacv/LiFZMA22":"WACV",
"https://dblp.org/rec/conf/wacv/LiLSZCT22":"WACV",
"https://dblp.org/rec/conf/wacv/LiLXH22":"WACV",
"https://dblp.org/rec/conf/wacv/LiMO22":"WACV",
"https://dblp.org/rec/conf/wacv/LiW022":"WACV",
"https://dblp.org/rec/conf/wacv/LiXHLG22":"WACV",
"https://dblp.org/rec/conf/wacv/LiZLVR22":"WACV",
"https://dblp.org/rec/conf/wacv/LinRWCW22":"WACV",
"https://dblp.org/rec/conf/wacv/LinYSS22":"WACV",
"https://dblp.org/rec/conf/wacv/LiuGI0V22":"WACV",
"https://dblp.org/rec/conf/wacv/LiuHLM22":"WACV",
"https://dblp.org/rec/conf/wacv/LiuZB22":"WACV",
"https://dblp.org/rec/conf/wacv/LohitJ22":"WACV",
"https://dblp.org/rec/conf/wacv/Long022":"WACV",
"https://dblp.org/rec/conf/wacv/LongHWP22":"WACV",
"https://dblp.org/rec/conf/wacv/LuL22":"WACV",
"https://dblp.org/rec/conf/wacv/Lyu0Z22":"WACV",
"https://dblp.org/rec/conf/wacv/MaDS22":"WACV",
"https://dblp.org/rec/conf/wacv/MaharjanY22":"WACV",
"https://dblp.org/rec/conf/wacv/MaheshwariGS22":"WACV",
"https://dblp.org/rec/conf/wacv/MajithiaPBGSS22":"WACV",
"https://dblp.org/rec/conf/wacv/MakabeSOM22":"WACV",
"https://dblp.org/rec/conf/wacv/MakrigiorgisHKT22":"WACV",
"https://dblp.org/rec/conf/wacv/MallBBG22":"WACV",
"https://dblp.org/rec/conf/wacv/MamanB22":"WACV",
"https://dblp.org/rec/conf/wacv/ManglaCBK22":"WACV",
"https://dblp.org/rec/conf/wacv/ManglaK0KB22":"WACV",
"https://dblp.org/rec/conf/wacv/MathewBTKVJ22":"WACV",
"https://dblp.org/rec/conf/wacv/MatsubaraYLM22":"WACV",
"https://dblp.org/rec/conf/wacv/MazaheriR22":"WACV",
"https://dblp.org/rec/conf/wacv/MazumderSN22":"WACV",
"https://dblp.org/rec/conf/wacv/MeryM22":"WACV",
"https://dblp.org/rec/conf/wacv/MicheliniLJ22":"WACV",
"https://dblp.org/rec/conf/wacv/MoghaddamA0SH22":"WACV",
"https://dblp.org/rec/conf/wacv/MoolchandaniSKS22":"WACV",
"https://dblp.org/rec/conf/wacv/MoreauPTSF22":"WACV",
"https://dblp.org/rec/conf/wacv/NaderiSHQ22":"WACV",
"https://dblp.org/rec/conf/wacv/NarasimhanGOED22":"WACV",
"https://dblp.org/rec/conf/wacv/NeekharaHDDKM22":"WACV",
"https://dblp.org/rec/conf/wacv/NguyenPD22":"WACV",
"https://dblp.org/rec/conf/wacv/Nie0022":"WACV",
"https://dblp.org/rec/conf/wacv/OBrienMBH22":"WACV",
"https://dblp.org/rec/conf/wacv/OhKBHL22":"WACV",
"https://dblp.org/rec/conf/wacv/OsahorN22":"WACV",
"https://dblp.org/rec/conf/wacv/OttRHBM22":"WACV",
"https://dblp.org/rec/conf/wacv/Pan0CECBSPR22":"WACV",
"https://dblp.org/rec/conf/wacv/PangMR22":"WACV",
"https://dblp.org/rec/conf/wacv/ParidaSS22":"WACV",
"https://dblp.org/rec/conf/wacv/PeeplesMWSZ22":"WACV",
"https://dblp.org/rec/conf/wacv/PengAS22":"WACV",
"https://dblp.org/rec/conf/wacv/PengZWM22":"WACV",
"https://dblp.org/rec/conf/wacv/Perez-YusA22":"WACV",
"https://dblp.org/rec/conf/wacv/PestanaARSM22":"WACV",
"https://dblp.org/rec/conf/wacv/PetersenGDK22":"WACV",
"https://dblp.org/rec/conf/wacv/PetrovaiN22":"WACV",
"https://dblp.org/rec/conf/wacv/PhilippAGMSRM22":"WACV",
"https://dblp.org/rec/conf/wacv/PicekSMJHLF22":"WACV",
"https://dblp.org/rec/conf/wacv/PiersonDT22":"WACV",
"https://dblp.org/rec/conf/wacv/PramanickRP22":"WACV",
"https://dblp.org/rec/conf/wacv/Przewiezlikowski22":"WACV",
"https://dblp.org/rec/conf/wacv/PucciMFM22":"WACV",
"https://dblp.org/rec/conf/wacv/RaiS0BSJ22":"WACV",
"https://dblp.org/rec/conf/wacv/RajaMV22":"WACV",
"https://dblp.org/rec/conf/wacv/RashidBAHAKL22":"WACV",
"https://dblp.org/rec/conf/wacv/ReedYNEVM0ZGMKD22":"WACV",
"https://dblp.org/rec/conf/wacv/RobbianoRGCC22":"WACV",
"https://dblp.org/rec/conf/wacv/RodriguesT22":"WACV",
"https://dblp.org/rec/conf/wacv/RudolphWRW22":"WACV",
"https://dblp.org/rec/conf/wacv/RukhovichV022":"WACV",
"https://dblp.org/rec/conf/wacv/SadekarTR22":"WACV",
"https://dblp.org/rec/conf/wacv/SalvatoreF22":"WACV",
"https://dblp.org/rec/conf/wacv/SanchezM22":"WACV",
"https://dblp.org/rec/conf/wacv/SarkarSB22":"WACV",
"https://dblp.org/rec/conf/wacv/SarnoKKHFG22":"WACV",
"https://dblp.org/rec/conf/wacv/ScheligaMS22":"WACV",
"https://dblp.org/rec/conf/wacv/SeiskariRKYRS22":"WACV",
"https://dblp.org/rec/conf/wacv/SenocakR0K22":"WACV",
"https://dblp.org/rec/conf/wacv/ShabanRAB022":"WACV",
"https://dblp.org/rec/conf/wacv/ShahMBCCS22":"WACV",
"https://dblp.org/rec/conf/wacv/ShamsafarWRZ22":"WACV",
"https://dblp.org/rec/conf/wacv/SharmaAK22":"WACV",
"https://dblp.org/rec/conf/wacv/SharmaMA22":"WACV",
"https://dblp.org/rec/conf/wacv/ShiM22":"WACV",
"https://dblp.org/rec/conf/wacv/ShiMHJJS22":"WACV",
"https://dblp.org/rec/conf/wacv/ShiSLLL22":"WACV",
"https://dblp.org/rec/conf/wacv/ShresthaKK22":"WACV",
"https://dblp.org/rec/conf/wacv/SimonKH22":"WACV",
"https://dblp.org/rec/conf/wacv/SimonKPHH22":"WACV",
"https://dblp.org/rec/conf/wacv/SinhaNK22":"WACV",
"https://dblp.org/rec/conf/wacv/SipkaSM22":"WACV",
"https://dblp.org/rec/conf/wacv/SlimB0O22":"WACV",
"https://dblp.org/rec/conf/wacv/SongHA22":"WACV",
"https://dblp.org/rec/conf/wacv/SouibguiBDFKGK022":"WACV",
"https://dblp.org/rec/conf/wacv/SpethVFBC22":"WACV",
"https://dblp.org/rec/conf/wacv/StackerHRS22":"WACV",
"https://dblp.org/rec/conf/wacv/StoffregenDRF22":"WACV",
"https://dblp.org/rec/conf/wacv/SunPG22":"WACV",
"https://dblp.org/rec/conf/wacv/SunZB22":"WACV",
"https://dblp.org/rec/conf/wacv/SuvorovLMRASKGP22":"WACV",
"https://dblp.org/rec/conf/wacv/SzaszHLLRA22":"WACV",
"https://dblp.org/rec/conf/wacv/SzymanowiczCC22":"WACV",
"https://dblp.org/rec/conf/wacv/TalrejaNV22":"WACV",
"https://dblp.org/rec/conf/wacv/TanGL22":"WACV",
"https://dblp.org/rec/conf/wacv/TanK22":"WACV",
"https://dblp.org/rec/conf/wacv/TanfousZLS22":"WACV",
"https://dblp.org/rec/conf/wacv/TanjimSSMASC22":"WACV",
"https://dblp.org/rec/conf/wacv/TaveraCMC22":"WACV",
"https://dblp.org/rec/conf/wacv/TheinerGMRME22":"WACV",
"https://dblp.org/rec/conf/wacv/TheinerME22":"WACV",
"https://dblp.org/rec/conf/wacv/TiwariKVC22":"WACV",
"https://dblp.org/rec/conf/wacv/TiwariMAB22":"WACV",
"https://dblp.org/rec/conf/wacv/TjioLZG22":"WACV",
"https://dblp.org/rec/conf/wacv/ToeringGSH22":"WACV",
"https://dblp.org/rec/conf/wacv/TomesekCB22":"WACV",
"https://dblp.org/rec/conf/wacv/TrehanA22":"WACV",
"https://dblp.org/rec/conf/wacv/TripathyKR22":"WACV",
"https://dblp.org/rec/conf/wacv/TsaiWL22":"WACV",
"https://dblp.org/rec/conf/wacv/TursynbekPO22":"WACV",
"https://dblp.org/rec/conf/wacv/UddinC22":"WACV",
"https://dblp.org/rec/conf/wacv/VSPYHP22":"WACV",
"https://dblp.org/rec/conf/wacv/VaidyaSM22":"WACV",
"https://dblp.org/rec/conf/wacv/VargaKMZ22":"WACV",
"https://dblp.org/rec/conf/wacv/VasudevaDBP22":"WACV",
"https://dblp.org/rec/conf/wacv/VavilalaF22":"WACV",
"https://dblp.org/rec/conf/wacv/VoSN22":"WACV",
"https://dblp.org/rec/conf/wacv/WanCAJYL22":"WACV",
"https://dblp.org/rec/conf/wacv/WanREC22":"WACV",
"https://dblp.org/rec/conf/wacv/WangCLLXTF22":"WACV",
"https://dblp.org/rec/conf/wacv/WangFP22":"WACV",
"https://dblp.org/rec/conf/wacv/WangK22":"WACV",
"https://dblp.org/rec/conf/wacv/WangL22":"WACV",
"https://dblp.org/rec/conf/wacv/WangQC22":"WACV",
"https://dblp.org/rec/conf/wacv/WangTHDL022":"WACV",
"https://dblp.org/rec/conf/wacv/WangWCV22":"WACV",
"https://dblp.org/rec/conf/wacv/WangWL22":"WACV",
"https://dblp.org/rec/conf/wacv/WeiLXKG22":"WACV",
"https://dblp.org/rec/conf/wacv/WilsonLZFW22":"WACV",
"https://dblp.org/rec/conf/wacv/WongBKB0022":"WACV",
"https://dblp.org/rec/conf/wacv/Wu0XZLL22":"WACV",
"https://dblp.org/rec/conf/wacv/XiaXWZ22":"WACV",
"https://dblp.org/rec/conf/wacv/XiangLYZSA22":"WACV",
"https://dblp.org/rec/conf/wacv/XuKS022":"WACV",
"https://dblp.org/rec/conf/wacv/XuW0GZ22":"WACV",
"https://dblp.org/rec/conf/wacv/XuYLWWC22":"WACV",
"https://dblp.org/rec/conf/wacv/YanTSMKX22":"WACV",
"https://dblp.org/rec/conf/wacv/Yang0022":"WACV",
"https://dblp.org/rec/conf/wacv/YangBCPK22":"WACV",
"https://dblp.org/rec/conf/wacv/YangBZCJ22":"WACV",
"https://dblp.org/rec/conf/wacv/YangBZGS22":"WACV",
"https://dblp.org/rec/conf/wacv/YangHGR22":"WACV",
"https://dblp.org/rec/conf/wacv/YangZDT0Y22":"WACV",
"https://dblp.org/rec/conf/wacv/YaoGQCZ022":"WACV",
"https://dblp.org/rec/conf/wacv/YeYM22":"WACV",
"https://dblp.org/rec/conf/wacv/YinLSARK22":"WACV",
"https://dblp.org/rec/conf/wacv/YoonKC22":"WACV",
"https://dblp.org/rec/conf/wacv/YouHF0TF22":"WACV",
"https://dblp.org/rec/conf/wacv/YuLCS022":"WACV",
"https://dblp.org/rec/conf/wacv/YuWCKSYLLS022":"WACV",
"https://dblp.org/rec/conf/wacv/YuYGDKMK22":"WACV",
"https://dblp.org/rec/conf/wacv/YuanLWBCC22":"WACV",
"https://dblp.org/rec/conf/wacv/YucerTMB22":"WACV",
"https://dblp.org/rec/conf/wacv/YunT22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhangBCP22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhangBCWBJP22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhangC22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhangDZWS22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhangFLA22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhaoL22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhengP22":"WACV",
"https://dblp.org/rec/conf/wacv/ZhongWFZSY22":"WACV",
"https://dblp.org/rec/conf/wacv/ZouHL22":"WACV",
"https://dblp.org/rec/conf/wacv/ZustK22":"WACV",
"https://dblp.org/rec/conf/wacv/0001HDK22":"WACV",
"https://dblp.org/rec/conf/wacv/0005XV22":"WACV",
"https://dblp.org/rec/conf/wacv/0009CK22":"WACV",
"https://dblp.org/rec/conf/wacv/0029AML22":"WACV",
"https://dblp.org/rec/conf/wacv/AfifiBB22":"WACV",
"https://dblp.org/rec/conf/wacv/AgarwalMA022":"WACV",
"https://dblp.org/rec/conf/wacv/AzimiPRHB022":"WACV",
"https://dblp.org/rec/conf/wacv/BammeyGM22":"WACV",
"https://dblp.org/rec/conf/wacv/BealWPZK22":"WACV",
"https://dblp.org/rec/conf/wacv/ChenH22":"WACV",
"https://dblp.org/rec/conf/wacv/ChenJS022":"WACV",
"https://dblp.org/rec/conf/wacv/ChiuG22":"WACV",
"https://dblp.org/rec/conf/wacv/ChowdhuryCCJ22":"WACV",
"https://dblp.org/rec/conf/wacv/ChungC22":"WACV",
"https://dblp.org/rec/conf/wacv/DashB022":"WACV",
"https://dblp.org/rec/conf/wacv/DegardinNLBY022":"WACV",
"https://dblp.org/rec/conf/wacv/EmadPC22":"WACV",
"https://dblp.org/rec/conf/wacv/FadaduPHSCDV22":"WACV",
"https://dblp.org/rec/conf/wacv/FangDKK22":"WACV",
"https://dblp.org/rec/conf/wacv/FeleLPS22":"WACV",
"https://dblp.org/rec/conf/wacv/FischerSMM22":"WACV",
"https://dblp.org/rec/conf/wacv/GaoL22":"WACV",
"https://dblp.org/rec/conf/wacv/GargBSA22":"WACV",
"https://dblp.org/rec/conf/wacv/GargSB0SJ22":"WACV",
"https://dblp.org/rec/conf/wacv/GudovskiyIK22":"WACV",
"https://dblp.org/rec/conf/wacv/GuoLLDQX22":"WACV",
"https://dblp.org/rec/conf/wacv/GuptaPTS22":"WACV",
"https://dblp.org/rec/conf/wacv/HahnerG22":"WACV",
"https://dblp.org/rec/conf/wacv/HuVH22":"WACV",
"https://dblp.org/rec/conf/wacv/HuangB22":"WACV",
"https://dblp.org/rec/conf/wacv/JiangGWSYW22":"WACV",
"https://dblp.org/rec/conf/wacv/KhodadadehGMLBK22":"WACV",
"https://dblp.org/rec/conf/wacv/KimK22":"WACV",
"https://dblp.org/rec/conf/wacv/KimLLKK22":"WACV",
"https://dblp.org/rec/conf/wacv/KimNPJL22":"WACV",
"https://dblp.org/rec/conf/wacv/KollingMGPPB22":"WACV",
"https://dblp.org/rec/conf/wacv/KrasnerSRCMKMVS22":"WACV",
"https://dblp.org/rec/conf/wacv/LambaM22":"WACV",
"https://dblp.org/rec/conf/wacv/LeeK022":"WACV",
"https://dblp.org/rec/conf/wacv/LeeLS22":"WACV",
"https://dblp.org/rec/conf/wacv/LeeYJ22":"WACV",
"https://dblp.org/rec/conf/wacv/LugmayrDYGT22":"WACV",
"https://dblp.org/rec/conf/wacv/MemmesheimerHTP22":"WACV",
"https://dblp.org/rec/conf/wacv/MinamiSOM22":"WACV",
"https://dblp.org/rec/conf/wacv/MustafaMIBM22":"WACV",
"https://dblp.org/rec/conf/wacv/NayakRC22":"WACV",
"https://dblp.org/rec/conf/wacv/NestiRNBB22":"WACV",
"https://dblp.org/rec/conf/wacv/NguyenNTP22":"WACV",
"https://dblp.org/rec/conf/wacv/OstonovWM22":"WACV",
"https://dblp.org/rec/conf/wacv/PalBSBJ22":"WACV",
"https://dblp.org/rec/conf/wacv/ParkCLL22":"WACV",
"https://dblp.org/rec/conf/wacv/PlanamentePAC22":"WACV",
"https://dblp.org/rec/conf/wacv/RoyF22":"WACV",
"https://dblp.org/rec/conf/wacv/SahuSD22":"WACV",
"https://dblp.org/rec/conf/wacv/Shukla22":"WACV",
"https://dblp.org/rec/conf/wacv/TezcanDCIK22":"WACV",
"https://dblp.org/rec/conf/wacv/TomarBLVRT22":"WACV",
"https://dblp.org/rec/conf/wacv/WeylerMSBS22":"WACV",
"https://dblp.org/rec/conf/wacv/XieKWYCZV22":"WACV",
"https://dblp.org/rec/conf/wacv/XingETT22":"WACV",
"https://dblp.org/rec/conf/wacv/YangRZL22":"WACV",
"https://dblp.org/rec/conf/wacv/YeZLZ0F22":"WACV",
"https://dblp.org/rec/conf/wacv/YinHTKZN22":"WACV",
"https://dblp.org/rec/conf/wacv/ZheltonozhskiiB22":"WACV",
"https://dblp.org/rec/conf/vmcai/ArceriOCF22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/BartocciFHNC22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/BayaniM22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/Ernst22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/FuHLSSTZ22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/GoldbaumMEBM22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/HeckSJMK22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/JensenSUV22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/LiuWZ22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/MirliazP22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/NicoleLR22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/OnderkaR22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/PolgreenRS22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/Prabhakar22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/RayaK22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/RobertsNBMZ22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/SchmidK22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/SeufertSCRW22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/TaylorZ22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/TrimanandaLDX22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/WesleyCNTWG22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/WinklerLK22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/WuBWRXL22":"VMCAI",
"https://dblp.org/rec/conf/vmcai/ZoharIMNNPRBT22":"VMCAI",
"https://dblp.org/rec/conf/fedcsis/AiderBH20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/Alihodzic20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/BendaliKMQT20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/GotsovT20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/StepanekHMM20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TodorovDOZGP20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TranevaT20b":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/AndonovPS20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/DezertFT20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/DorpinghausS20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/FidanovaRG20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/GoullieuxHS20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/Grigoreva20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/HosseiniWT20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/LiFMRTT20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/MikhovMKSMSF20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/Mucherino20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/MyasnichenkoMKS20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/RiosXMA20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/Todorov20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TodorovADDPT20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TodorovDMDP20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TodorovDOZGP20a":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TodorovDP20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TodorovFDPAT20":"WCO@FedCSIS",
"https://dblp.org/rec/conf/fedcsis/TranevaT20c":"WCO@FedCSIS",
"https://dblp.org/rec/conf/rweb/Bertossi21":"Reasoning Web",
"https://dblp.org/rec/conf/rweb/Cabalar21":"Reasoning Web",
"https://dblp.org/rec/conf/rweb/Figueira21":"Reasoning Web",
"https://dblp.org/rec/conf/rweb/Knorr21":"Reasoning Web",
"https://dblp.org/rec/conf/rweb/Pareti021":"Reasoning Web",
"https://dblp.org/rec/conf/rweb/SchockaertG21":"Reasoning Web",
"https://dblp.org/rec/conf/icqe/2021":"Communications in Computer and Information Science",
"https://dblp.org/rec/conf/enase/2021s":"Communications in Computer and Information Science",
"https://dblp.org/rec/conf/bnaic/2021s":"Communications in Computer and Information Science",
"https://dblp.org/rec/conf/icwe/2021w":"Communications in Computer and Information Science",
"https://dblp.org/rec/conf/mobisec2/2021":"Communications in Computer and Information Science",
"https://dblp.org/rec/conf/grapp/2020s":"Communications in Computer and Information Science",
"https://dblp.org/rec/conf/icqe/AlzahraniTKMJAG21":"ICQE",
"https://dblp.org/rec/conf/icqe/AndresHOBNP21":"ICQE",
"https://dblp.org/rec/conf/icqe/BaranyPKO21":"ICQE",
"https://dblp.org/rec/conf/icqe/BennaR21":"ICQE",
"https://dblp.org/rec/conf/icqe/BresslerADLV21":"ICQE",
"https://dblp.org/rec/conf/icqe/CarmonaGM21":"ICQE",
"https://dblp.org/rec/conf/icqe/EspinoTLPHOLM21":"ICQE",
"https://dblp.org/rec/conf/icqe/HamiltonLCM21":"ICQE",
"https://dblp.org/rec/conf/icqe/Knowles21":"ICQE",
"https://dblp.org/rec/conf/icqe/LevineES21":"ICQE",
"https://dblp.org/rec/conf/icqe/MohammadhassanM21":"ICQE",
"https://dblp.org/rec/conf/icqe/NachtigallNS21":"ICQE",
"https://dblp.org/rec/conf/icqe/Nguyen21":"ICQE",
"https://dblp.org/rec/conf/icqe/NohrLHSM21":"ICQE",
"https://dblp.org/rec/conf/icqe/NyiroFHHZ21":"ICQE",
"https://dblp.org/rec/conf/icqe/SchnaiderSS21":"ICQE",
"https://dblp.org/rec/conf/icqe/SciannaKBZ21":"ICQE",
"https://dblp.org/rec/conf/icqe/ShafferEKPC21":"ICQE",
"https://dblp.org/rec/conf/icqe/ShahSME21":"ICQE",
"https://dblp.org/rec/conf/icqe/Siebert-Evenstone21":"ICQE",
"https://dblp.org/rec/conf/icqe/Swiecki21":"ICQE",
"https://dblp.org/rec/conf/icqe/TanHMRS21":"ICQE",
"https://dblp.org/rec/conf/icqe/VegaI21":"ICQE",
"https://dblp.org/rec/conf/icqe/WrightOEL021":"ICQE",
"https://dblp.org/rec/conf/icqe/ZorgoJCMS21":"ICQE",
"https://dblp.org/rec/conf/icqe/ZorgoPPMDE21":"ICQE",
"https://dblp.org/rec/conf/lfcs/AguileraBF22":"LFCS",
"https://dblp.org/rec/conf/lfcs/BaazL22":"LFCS",
"https://dblp.org/rec/conf/lfcs/CenzerK22":"LFCS",
"https://dblp.org/rec/conf/lfcs/DeBoer22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Forster22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Kjos-HanssenNY22":"LFCS",
"https://dblp.org/rec/conf/lfcs/LehnherrOS22":"LFCS",
"https://dblp.org/rec/conf/lfcs/LiuS22":"LFCS",
"https://dblp.org/rec/conf/lfcs/MotouraK22":"LFCS",
"https://dblp.org/rec/conf/lfcs/NormannS22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Petrakis22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Sanders22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Sedlar22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Statman22":"LFCS",
"https://dblp.org/rec/conf/lfcs/TrottaSP22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Zielenkiewicz22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Fernandez-Duque22":"LFCS",
"https://dblp.org/rec/conf/lfcs/HagemeierK22":"LFCS",
"https://dblp.org/rec/conf/lfcs/KontinenMM22":"LFCS",
"https://dblp.org/rec/conf/lfcs/MarcelinoCF22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Moore22":"LFCS",
"https://dblp.org/rec/conf/lfcs/Rogozin22":"LFCS",
"https://dblp.org/rec/conf/lfcs/SubramaniW22":"LFCS",
"https://dblp.org/rec/conf/ttc/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/benevol/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/ssi/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/gvd/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/aiia/2021ips":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/semweb/2021om":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/ectel/2021dc":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/aaaifs/2021human":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/icteri/2021cosine":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/wilf/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/ims2/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/tacc/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/ictcs/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/icbo/2021":"CEUR Workshop Proceedings",
"https://dblp.org/rec/conf/ttc/Beurer-KellnerP21":"TTC/",
"https://dblp.org/rec/conf/ttc/Boronat21":"TTC/",
"https://dblp.org/rec/conf/ttc/Boronat21a":"TTC/",
"https://dblp.org/rec/conf/ttc/CopeiZ21":"TTC/",
"https://dblp.org/rec/conf/ttc/Garcia-Domiguez21":"TTC/",
"https://dblp.org/rec/conf/ttc/Hinkel21":"TTC/",
"https://dblp.org/rec/conf/ttc/Hinkel21a":"TTC/",
"https://dblp.org/rec/conf/ttc/Hinkel21b":"TTC/",
"https://dblp.org/rec/conf/ttc/Hinkel21c":"TTC/",
"https://dblp.org/rec/conf/ttc/JouaultC21":"TTC/",
"https://dblp.org/rec/conf/ttc/NguyenGC21":"TTC/",
"https://dblp.org/rec/conf/ttc/Struber21":"TTC/",
"https://dblp.org/rec/conf/comad/0001M22":"COMAD/CODS",
"https://dblp.org/rec/conf/comad/0002BM22":"COMAD/CODS",
"https://dblp.org/rec/conf/comad/AAHS22":"COMAD/CODS",
"https://dblp.org/rec/conf/comad/AR22":"COMAD/CODS"}
    return dic_results


if __name__ == "__main__":
    run(app,host=HOST,port=PORT)

